# Cyclic workflow to run the AstronomyDatabaseWriter

name: Execute AstronomyDatabaseWriter

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 6 * * SAT'
  workflow_dispatch:


jobs:
  write-database:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AstronomyDatabaseWriter
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install
    - name: Run ADW
      env:
        DATABASE_REPOSITORY_TOKEN: ${{ secrets.DATABASE_REPOSITORY_TOKEN }}
      run: pipenv run python astrodbwriter
